# Generated by Django 6.0.1 on 2026-01-28 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("route_number", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Sacco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("emergency_contact", models.CharField(default="999", max_length=15)),
                ("harassment_hotline", models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("landmark", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RouteStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_order", models.PositiveIntegerField()),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="transit.route"
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="transit.stage"
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_order"],
            },
        ),
        migrations.CreateModel(
            name="FareSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_slot",
                    models.CharField(
                        choices=[
                            ("MORNING_PEAK", "6 AM - 10 AM"),
                            ("OFF_PEAK", "10 AM - 4 PM"),
                            ("EVENING_PEAK", "4 PM - 8 PM"),
                            ("NIGHT", "8 PM - 6 AM"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.IntegerField()),
                (
                    "route_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fares",
                        to="transit.routestage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FareReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reported_price", models.IntegerField()),
                ("phone_number", models.CharField(max_length=15)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "route_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="transit.routestage",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="route",
            name="sacco",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="transit.sacco"
            ),
        ),
        migrations.CreateModel(
            name="SafetyIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("HARASSMENT", "Harassment/Abuse"),
                            ("EMERGENCY", "General Emergency/Accident"),
                            ("THEFT", "Theft/Robbery"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("details", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transit.route",
                    ),
                ),
                (
                    "sacco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="transit.sacco",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="route",
            name="stages",
            field=models.ManyToManyField(
                through="transit.RouteStage", to="transit.stage"
            ),
        ),
    ]
