# Generated by Django 6.0.1 on 2026-01-28 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LostItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_phone", models.CharField(max_length=15)),
                ("description", models.TextField()),
                (
                    "plate_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sacco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="transit.sacco"
                    ),
                ),
            ],
        ),
    ]
